### ISSUE TITLE
Remove offensive terminology

### ISSUE THREAD

**Issue by SuborbitalPigeon** [will-jj/matlab-image-viewer#1]
Obviously when people see a branch called 'master', they can only think that the author is supporting the slave trade and the confederate states. This should be fixed.

Also, 'commits' should be renamed to something else, as it mocks people with mental issues.

**Comment by will-jj** [comment]
I have renamed master to mainline.

**Comment by SuborbitalPigeon** [comment]
For the record, I was taking the piss.
